name: Trigger Content Build

on:
  push:
    branches:
      - main

jobs:
  build-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Content Repository
        uses: actions/checkout@v2

      - name: Trigger Content Build Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.CODINGSIMBA }}" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/christophersesugh/codingsimba/dispatches \
            -d '{"event_type": "content-build"}'
